config/routes.rb
Rails.application.routes.draw do
  resources :routes

  root 'routes#index'

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  def index
    

    p params
    
    if params[:search].present?
      imei = params[:search][:imei_text]
      imei = params[:search][:imei_select] if imei.blank?
    else
      imei = nil
    end

    p "imei: #{imei}"


    # получаем TDRы
    p @info = TimeDataRoute.search(params[:search], imei)
    # @info = nil

    # получаем точки для отображения на карте
    p data_points = Point.search(params[:search], imei)

    if data_points.present? && data_points.size > 0
      p @points = data_points
      p @points_map = @points.map{|x| {"lat" => x.lat, "lon" => x.lon}}.to_json

      p @begin_point = data_points.first
      p @end_point = data_points.last

      if params[:search].blank?
        @points = []
        @points_map = []
        @info = nil
      end

      respond_to do |format|
        format.json { render :json => { tdrs: @info.to_json, points: @points } }
        format.js
        format.html
      end
    else
      respond_to do |format|
        format.js { render 'empty' }
        format.html
      end
    end
  end

end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.slim
= simple_form_for @route, :html => { :class => "form-horizontal" } do |f|
  = f.button :submit, :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), routes_path, :class => 'btn btn-default'

app/views/routes/_points.html.slim
.panel.panel-default
  .panel-heading.text-center
    strong
      = "Параметры маршрута"
  .panel-body style="padding:0px;"
    table.table
      tbody
        tr
          td style="width:50%;"
            strong = "Общая стоимость по федеральным трассам:"
          td.text-right
            #sum
            = "#{@info[:total_price] if @info && @info[:total_price]} р."
        tr
          td
            strong = "Пройдено всего: "
          td.text-right
            #totalWay
              span.total_way
              ="км"
        tr
          td
            #price
              strong
                = "Пройдено по федеральным трассам:"
          td.text-right = "#{@info[:total_distance].round() if @info && @info[:total_distance]} км."
        /tr
          td = "Координаты начала пути: "
          td.text-right
            #begin_point_coord
              = "#{@begin_point if @points.count > 0}"
        tr
          td
            strong
              = "Начало пути: "
          td
            #begin_point
              span.begin_point
                = @begin_point if @points.count > 0
        /tr
          td = "Координаты конца пути: "
          td.text-right
            #end_point_coord
              = "#{@end_point if @points.count > 0}"
        tr
          td
            strong
              = "Конец пути: "
          td
            #end_point
              span.end_point
                = @end_point if @points.count > 0




/table.table.table-striped.table-bordered.table-hover
  thead
    th Время
    th Широта
    th Долгота
    th Транспортное средство (ID)
  tbody
    -@points.each do |point|
      tr
        td = l Time.at(point.time).to_datetime, format: :long
        td = point['lat']
        td = point['lon']
        td

app/views/routes/edit.html.slim
- model_class = Route
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/routes/empty.js.erb
$("#points").html("Информация по данному IMEI отсутствует");
$("#map").attr("points", '[{"lat":1,"lon":1}]');
var osrm_server = "http://nominatim.openstreetmap.org/";
$.get(osrm_server + "reverse?format=json&lat=1&lon=1", function( data ) {
        $("span.begin_point").html(data["display_name"]);
    });
drawPath();

app/views/routes/index.html.slim
.container style="margin-top:40px;"
  .panel.panel-info
    .panel-heading
      h4
        = "Построение маршрута транспортного средства"
    .panel-body
      .container-fluid
        =form_tag routes_path, method: :get, :class => "form-inline", remote: true, id: "route-form" do
          =>label_tag "imei"
          =>select_tag "search[imei_select]",options_for_select([["4000001", "4000001"], ["999", "999"]], (params[:search][:imei_select] if params[:search]))
          'или
          =>text_field_tag "search[imei_text]", (params[:search][:imei_text] if params[:search]), class: "form-control"
          'приоритет текстовому полю
          br
          br
          .form-group
            => label_tag " С "
            =>text_field_tag "search[date_from]", (params[:search][:date_from] if params[:search]), class: "datetime form-control"
          .form-group
            span
              ="&nbsp;".html_safe
          .form-group
            => label_tag " По "
            =>text_field_tag "search[date_to]", (params[:search][:date_to] if params[:search]), :id => "date_to", class: "datetime form-control", :disabled => params[:is_online]
          .form-group style="margin-left:10px;"
            => label_tag  " В реальном времени"
            => label_tag
                span style="color:red;"
                  = '*'
            => check_box_tag "is_online", params[:is_online], params[:is_online], id: "is_online"
            =>submit_tag " Построить ", :class => "btn btn-primary", id: "route-form", style:"padding-left:35px;padding-right:35px;"
        br
        .col-md-12
          p
            small
              em
                span style="color:red;"
                  = '*'
                = " для построения пути транспортного средства с учетом текущих данных необходимо поставить галочку в чекбоксе"
      .col-md-5
        #points
          = render 'points' if @points.present?

      .col-md-7.panel.panel-default style="padding:0px;"
        #map data-points=@points_map points="[]" style="overflow: hidden; width: 100%; height: 500px; left: 0%; top: 50px"
            /button  onclick="drawPathExample()" построить путь
            /button  onclick="continuePathExample()" Дополнить путь

app/views/routes/index.js.erb
<% if @points.present? %>
  $("#points").html("<%= escape_javascript(render("points")) %>");
<% end %>

$("#map").attr("points", '<%= raw @points_map %>');


var osrm_server = "http://nominatim.openstreetmap.org/";


<% if @begin_point %>
    $.get(osrm_server + "reverse?format=json&lat=<%= escape_javascript(@begin_point['lat'].to_s) %>&lon=<%= escape_javascript(@begin_point['lon'].to_s) %>", function( data ) {
        $("span.begin_point").html(data["display_name"]);
    });
<% end %>

<% if @end_point %>
    $.get(osrm_server + "reverse?format=json&lat=<%= escape_javascript(@end_point['lat'].to_s) %>&lon=<%= escape_javascript(@end_point['lon'].to_s) %>", function( data ) {
        $("span.end_point").html(data["display_name"]);
    });
<% end %>

drawPath();

app/views/routes/new.html.slim
- model_class = Route
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/routes/show.html.slim
- model_class = Route
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize


= link_to t('.back', :default => t("helpers.links.back")), routes_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_route_path(@route), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), route_path(@route), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'